Repository input-output-hk/iohk-monitoring-framework, pull requests merged in 2019-03, with the labels that each got.

#147 [#8] Conditional compilation: disable-aggregation flag.
  docs/IOHK-Monitoring.pdf
  examples/complex/Main.lhs
  iohk-monitoring.cabal
  nix/.stack.nix/iohk-monitoring.nix
  src/Cardano/BM/Configuration/Static.lhs
  src/Cardano/BM/Data/BackendKind.lhs
  src/Cardano/BM/Output/Switchboard.lhs
  test/Cardano/BM/Test/Configuration.lhs
  test/Test.lhs
Labels: enhancement

#153 reenable building the code and running tests
  .buildkite/pipeline.yml
  iohk-monitoring.cabal
  shell.nix
  test/Cardano/BM/Test/Configuration.lhs
Labels: CI, nix

#150 [#8] Conditional compilation: disable-ekg flag.
  docs/IOHK-Monitoring.pdf
  examples/complex/Main.lhs
  iohk-monitoring.cabal
  nix/.stack.nix/iohk-monitoring.nix
  src/Cardano/BM/Data/Configuration.lhs
  src/Cardano/BM/Output/Switchboard.lhs
  test/Cardano/BM/Test/Configuration.lhs
  test/config.yaml
Labels: enhancement

#154 [#8] Conditional compilation: disable-gui flag.
  docs/IOHK-Monitoring.pdf
  examples/complex/Main.lhs
  iohk-monitoring.cabal
  nix/.stack.nix/iohk-monitoring.nix
Labels: enhancement

#129 [Devops 1222] haskell nix update
  nix/iohk-nix-src.json
  nix/pkgs.nix
  stack.yaml
Labels: CI, nix

#156 [#155] cross compilation
  iohk-monitoring.cabal
  nix/.stack.nix/iohk-monitoring.nix
  shell.nix
  src/Cardano/BM/Rotator.lhs
Labels: CI, nix

#157 [#8] Conditional compilation: disable-monitoring flag.
  docs/IOHK-Monitoring.pdf
  iohk-monitoring.cabal
  nix/.stack.nix/iohk-monitoring.nix
  src/Cardano/BM/Output/Switchboard.lhs
  test/Test.lhs
Labels: enhancement

#161 [#8] Conditional compilation: disable-observables flag.
  docs/IOHK-Monitoring.pdf
  examples/complex/Main.lhs
  iohk-monitoring.cabal
  nix/.stack.nix/iohk-monitoring.nix
  src/Cardano/BM/Counters/Dummy.lhs
  src/Cardano/BM/Counters/Linux.lhs
  test/Cardano/BM/Test/Trace.lhs
Labels: enhancement

#163 [#155] testing on Windows
  src/Cardano/BM/Rotator.lhs
  src/references.fmt
  test/Cardano/BM/Test/Configuration.lhs
  test/Cardano/BM/Test/Rotator.lhs
  test/Cardano/BM/Test/Trace.lhs
Labels: test

#162 [#143] Remove LoggerName from TraceContext.
  src/Cardano/BM/Data/MessageCounter.lhs
  src/Cardano/BM/Data/Trace.lhs
  src/Cardano/BM/Output/Aggregation.lhs
  src/Cardano/BM/Output/EKGView.lhs
  src/Cardano/BM/Output/Switchboard.lhs
  src/Cardano/BM/Setup.lhs
  src/Cardano/BM/Trace.lhs
  test/Cardano/BM/Test/Trace.lhs
Labels: enhancement

#171 [#146] Remove traceType fromContext.
  examples/complex/Main.lhs
  src/Cardano/BM/Data/Trace.lhs
  src/Cardano/BM/Observer/Monadic.lhs
  src/Cardano/BM/Observer/STM.lhs
  src/Cardano/BM/Output/Aggregation.lhs
  src/Cardano/BM/Output/EKGView.lhs
  src/Cardano/BM/Output/Switchboard.lhs
  src/Cardano/BM/Setup.lhs
  src/Cardano/BM/Trace.lhs
  src/Code.lhs
  src/references.fmt
  test/Cardano/BM/Test/Trace.lhs
Labels: enhancement, wip

#184 Fix path to static content.
  iohk-monitoring/src/Cardano/BM/Configuration/Editor.lhs
Labels: bug

#172 LogBuffering backend
  docs/Code.lhs
  docs/Makefile
  iohk-monitoring/examples/complex/Main.lhs
  iohk-monitoring/iohk-monitoring.cabal
  iohk-monitoring/src/Cardano/BM/Configuration/Model.lhs
  iohk-monitoring/src/Cardano/BM/Data/Backend.lhs
  iohk-monitoring/src/Cardano/BM/Data/BackendKind.lhs
  iohk-monitoring/src/Cardano/BM/Data/LogItem.lhs
  iohk-monitoring/src/Cardano/BM/Observer/STM.lhs
  iohk-monitoring/src/Cardano/BM/Output/Aggregation.lhs
  iohk-monitoring/src/Cardano/BM/Output/LogBuffer.lhs
  iohk-monitoring/src/Cardano/BM/Output/Switchboard.lhs
  iohk-monitoring/src/Cardano/BM/Setup.lhs
Labels: enhancement
