Repository input-output-hk/iohk-monitoring-framework, pull requests merged in 2019-06, with the labels that each got.

#314 [#258] capture external log items
  docs/Code.lhs
  docs/IOHK-Monitoring.pdf
  docs/Makefile
  docs/references.fmt
  iohk-monitoring/examples/complex/Main.lhs
  iohk-monitoring/iohk-monitoring.cabal
  iohk-monitoring/src/Cardano/BM/Backend/Aggregation.lhs
  iohk-monitoring/src/Cardano/BM/Backend/EKGView.lhs
  iohk-monitoring/src/Cardano/BM/Backend/Editor.lhs
  iohk-monitoring/src/Cardano/BM/Backend/ExternalAbstraction.lhs
  iohk-monitoring/src/Cardano/BM/Backend/Log.lhs
  iohk-monitoring/src/Cardano/BM/Backend/LogBuffer.lhs
  iohk-monitoring/src/Cardano/BM/Backend/Monitoring.lhs
  iohk-monitoring/src/Cardano/BM/Backend/Prometheus.lhs
  iohk-monitoring/src/Cardano/BM/Backend/Switchboard.lhs
  iohk-monitoring/src/Cardano/BM/Backend/TraceAcceptor.lhs
  iohk-monitoring/src/Cardano/BM/Backend/TraceForwarder.lhs
  iohk-monitoring/src/Cardano/BM/Configuration.lhs
  iohk-monitoring/src/Cardano/BM/Configuration/Model.lhs
  iohk-monitoring/src/Cardano/BM/Data/Aggregated.lhs
  iohk-monitoring/src/Cardano/BM/Data/Backend.lhs
  iohk-monitoring/src/Cardano/BM/Data/BackendKind.lhs
  iohk-monitoring/src/Cardano/BM/Data/Configuration.lhs
  iohk-monitoring/src/Cardano/BM/Data/Counter.lhs
  iohk-monitoring/src/Cardano/BM/Data/LogItem.lhs
  iohk-monitoring/src/Cardano/BM/Observer/Monadic.lhs
  iohk-monitoring/src/Cardano/BM/Rotator.lhs
  iohk-monitoring/src/Cardano/BM/Setup.lhs
  iohk-monitoring/test/Cardano/BM/Test/Aggregated.lhs
  iohk-monitoring/test/Cardano/BM/Test/Configuration.lhs
  iohk-monitoring/test/Cardano/BM/Test/Trace.lhs
  iohk-monitoring/test/config.yaml
Labels: enhancement

#358 Fix types for bracketObserveIO (both IO and STM) in PDF.
  docs/IOHK-Monitoring.pdf
  docs/mu-benchmarks.tex
Labels: TeX, bug

#357 Add minimal flags build to CI and fix build error with -fdisable-syslog
  iohk-monitoring/src/Cardano/BM/Backend/Log.lhs
  iohk-monitoring/src/Cardano/BM/Configuration/Model.lhs
  nix/pkgs.nix
  release.nix
Labels: CI, bug

#359 set severity of #messagecounters to Debug; they're per default 'NoTrace'
  iohk-monitoring/src/Cardano/BM/Backend/Aggregation.lhs
  iohk-monitoring/src/Cardano/BM/Backend/EKGView.lhs
  iohk-monitoring/src/Cardano/BM/Backend/Graylog.lhs
  iohk-monitoring/src/Cardano/BM/Backend/Monitoring.lhs
  iohk-monitoring/src/Cardano/BM/Backend/Switchboard.lhs
  iohk-monitoring/src/Cardano/BM/Configuration/Model.lhs
Labels: staging

#360 Prometheus only listens on localhost
  iohk-monitoring/examples/complex/Main.lhs
  iohk-monitoring/src/Cardano/BM/Backend/Prometheus.lhs
Labels: bug, staging

#363 Fixed bugs in creating and opening pipes.
  iohk-monitoring/src/Cardano/BM/Backend/ExternalAbstraction.lhs
  iohk-monitoring/src/Cardano/BM/Backend/Switchboard.lhs
  iohk-monitoring/src/Cardano/BM/Backend/TraceAcceptor.lhs
  iohk-monitoring/src/Cardano/BM/Backend/TraceForwarder.lhs
Labels: bug

#364 PDF: tag 'spec' instead of 'verbatim'.
  docs/IOHK-Monitoring.pdf
  docs/mu-benchmarks.tex
Labels: TeX

#378 [#362] Point to ekg-prometheus-adapter's fork.
  cabal.project
Labels: bug, staging

#380 Fixed termination functions of backends.
  iohk-monitoring/src/Cardano/BM/Backend/EKGView.lhs
  iohk-monitoring/src/Cardano/BM/Backend/Graylog.lhs
  iohk-monitoring/src/Cardano/BM/Backend/Monitoring.lhs
  iohk-monitoring/src/Cardano/BM/Backend/Switchboard.lhs
  iohk-monitoring/src/Cardano/BM/Backend/TraceAcceptor.lhs
Labels: bug
