Repository input-output-hk/iohk-monitoring-framework, pull requests merged in 2019-05, with the labels that each got.

#261 repair findSubTrace to only check single name
  iohk-monitoring/src/Cardano/BM/Configuration/Model.lhs
Labels: bug

#213 [#207] Micro-benchmarking in tracer
  contra-tracer/contra-tracer.cabal
  contra-tracer/src/Control/Tracer/Observe.lhs
  iohk-monitoring/iohk-monitoring.cabal
  iohk-monitoring/src/Cardano/BM/Tracer.lhs
Labels: enhancement

#282 CI coverage
  .buildkite/pipeline.yml
  iohk-monitoring/README.md
  lib.nix
  scripts/buildkite/default.nix
  scripts/buildkite/rebuild.hs
  scripts/buildkite/stack-hpc-coveralls.nix
  scripts/nix/stack-shell.nix
  stack.yaml
Labels: CI

#285 [#268] Fix README and stack.yaml.
  README.md
  iohk-monitoring/README.md
  nix/.stack.nix/default.nix
  stack.yaml
Labels: CI

#296 make example-complex compile and run on MacOSX
  iohk-monitoring/examples/complex/Main.lhs
Labels: bug

#307 [#289] Renamed EKG values & forwarded LogValues properly.
  iohk-monitoring/src/Cardano/BM/Output/EKGView.lhs
  iohk-monitoring/src/Cardano/BM/Output/Switchboard.lhs
Labels: enhancement
