Repository input-output-hk/iohk-monitoring-framework, pull requests merged in 2019-04, with the labels that each got.

#209 [#201] Export configuration to file via GUI
  docs/references.fmt
  iohk-monitoring/iohk-monitoring.cabal
  iohk-monitoring/src/Cardano/BM/Configuration/Model.lhs
  iohk-monitoring/src/Cardano/BM/Output/Editor.lhs
  iohk-monitoring/test/Cardano/BM/Test/Configuration.lhs
  nix/.stack.nix/iohk-monitoring.nix
Labels: enhancement

#205 Improving documentation: contravariant explanation.
  docs/Code.lhs
  docs/IOHK-Monitoring.pdf
  docs/contravariant.tex
  iohk-monitoring/src/Cardano/BM/Data/Trace.lhs
Labels: TeX

#252 bug: bracketObserveIO should append name to named context
  iohk-monitoring/src/Cardano/BM/Observer/Monadic.lhs
  iohk-monitoring/src/Cardano/BM/Observer/STM.lhs
  iohk-monitoring/test/Cardano/BM/Test/Trace.lhs
Labels: bug
