Repository input-output-hk/iohk-monitoring-framework, pull requests merged in 2019-07, with the labels that each got.

#381 cabal: Rename disable-syslog to disable-systemd
  iohk-monitoring/iohk-monitoring.cabal
  iohk-monitoring/src/Cardano/BM/Backend/Log.lhs
  iohk-monitoring/src/Cardano/BM/Configuration/Model.lhs
  iohk-monitoring/src/Cardano/BM/Data/Output.lhs
  nix/.stack.nix/iohk-monitoring.nix
Labels: CI, bug

#387 [#257] Enable monitoring of external processes.
  iohk-monitoring/examples/complex/Main.lhs
  iohk-monitoring/src/Cardano/BM/Counters/Dummy.lhs
  iohk-monitoring/src/Cardano/BM/Counters/Linux.lhs
  iohk-monitoring/src/Cardano/BM/Data/SubTrace.lhs
  iohk-monitoring/src/Cardano/BM/Observer/Monadic.lhs
  iohk-monitoring/test/Cardano/BM/Test/Configuration.lhs
  iohk-monitoring/test/Cardano/BM/Test/Trace.lhs
  iohk-monitoring/test/config.yaml
Labels: enhancement

#388 Fix windows build
  iohk-monitoring/src/Cardano/BM/Data/SubTrace.lhs
  release.nix
Labels: bug

#394 [#347] Added multiple trace acceptors.
  iohk-monitoring/examples/simple/Main.lhs
  iohk-monitoring/src/Cardano/BM/Backend/ExternalAbstraction.lhs
  iohk-monitoring/src/Cardano/BM/Backend/Switchboard.lhs
  iohk-monitoring/src/Cardano/BM/Backend/TraceAcceptor.lhs
  iohk-monitoring/src/Cardano/BM/Data/BackendKind.lhs
  iohk-monitoring/test/Cardano/BM/Test/Configuration.lhs
  iohk-monitoring/test/config.yaml
Labels: staging

#396 [#395] Made appendName pure.
  iohk-monitoring/examples/complex/Main.lhs
  iohk-monitoring/examples/simple/Main.lhs
  iohk-monitoring/src/Cardano/BM/Backend/Aggregation.lhs
  iohk-monitoring/src/Cardano/BM/Backend/EKGView.lhs
  iohk-monitoring/src/Cardano/BM/Backend/Graylog.lhs
  iohk-monitoring/src/Cardano/BM/Backend/Monitoring.lhs
  iohk-monitoring/src/Cardano/BM/Backend/TraceAcceptor.lhs
  iohk-monitoring/src/Cardano/BM/Data/MessageCounter.lhs
  iohk-monitoring/src/Cardano/BM/Observer/Monadic.lhs
  iohk-monitoring/src/Cardano/BM/Observer/STM.lhs
  iohk-monitoring/src/Cardano/BM/Setup.lhs
  iohk-monitoring/src/Cardano/BM/Trace.lhs
  iohk-monitoring/test/Cardano/BM/Test/Monitoring.lhs
  iohk-monitoring/test/Cardano/BM/Test/Routing.lhs
  iohk-monitoring/test/Cardano/BM/Test/Trace.lhs
Labels: bug

#399 [#391] Added monitoring of bracketObserveIO.
  iohk-monitoring/examples/complex/Main.lhs
  iohk-monitoring/src/Cardano/BM/Backend/Monitoring.lhs
Labels: staging

#401 Get backends searches to root
  iohk-monitoring/src/Cardano/BM/Configuration/Model.lhs
  iohk-monitoring/test/Cardano/BM/Test/Configuration.lhs
  iohk-monitoring/test/config.yaml
Labels: bug

#402 Added timeouts for CI.
  .buildkite/pipeline.yml
Labels: CI
