Repository input-output-hk/iohk-monitoring-framework, pull requests merged in 2020-08, with the labels that each got.

#574 CAD-1208: Prometheus JSON output.
  examples/complex/Main.lhs
  plugins/backend-ekg/src/Cardano/BM/Backend/EKGView.lhs
  plugins/backend-ekg/src/Cardano/BM/Backend/Prometheus.lhs
Labels: enhancement

#576 fixing compilation on Windows
  iohk-monitoring/src/Cardano/BM/Rotator.lhs
Labels: bug, maintenance

#577 disable code coverage step in CI
  .buildkite/pipeline.yml
Labels: maintenance

#575 CAD-1407 stylish haskell
  .buildkite/check-stylish.sh
  .buildkite/pipeline.yml
  .stylish-haskell.yaml
  examples/acceptor/Main.hs
  iohk-monitoring/src/Cardano/BM/IOManager.hs
  iohk-monitoring/src/Cardano/BM/Snocket.hs
  iohk-monitoring/test/Cardano/BM/Arbitrary.hs
  nix/stack-shell.nix
  scripts/buildkite/rebuild.hs
  tracer-transformers/example1/Main.hs
  tracer-transformers/example2/Main.hs
  tracer-transformers/src/Control/Tracer/Transformers.hs
Labels: CI, maintenance
