Repository input-output-hk/iohk-monitoring-framework, pull requests merged in 2020-06, with the labels that each got.

#564 CAD-880: Forwarder and acceptor performance
  examples/complex/Main.lhs
  iohk-monitoring/src/Cardano/BM/Configuration.lhs
  iohk-monitoring/src/Cardano/BM/Configuration/Model.lhs
  iohk-monitoring/src/Cardano/BM/Data/Configuration.lhs
  iohk-monitoring/test/Cardano/BM/Test/Configuration.lhs
  iohk-monitoring/test/config.yaml
  plugins/backend-trace-acceptor/src/Cardano/BM/Backend/TraceAcceptor.lhs
  plugins/backend-trace-forwarder/src/Cardano/BM/Backend/TraceForwarder.lhs
Labels: help wanted

#565 CAD-1193 combined CPU usage time metric
  iohk-monitoring/src/Cardano/BM/Counters/Darwin.hsc
  iohk-monitoring/src/Cardano/BM/Counters/Linux.lhs
  iohk-monitoring/src/Cardano/BM/Counters/Windows.hsc
  iohk-monitoring/src/Cardano/BM/Counters/os-support-win.c
  iohk-monitoring/src/Cardano/BM/Counters/os-support-win.h
Labels: maintenance

#569 CAD-1247 set min and max severity filters on scribes
  examples/complex/Main.lhs
  examples/lobemo-examples.cabal
  examples/simple/Main.lhs
  iohk-monitoring/src/Cardano/BM/Backend/Log.lhs
  iohk-monitoring/src/Cardano/BM/Configuration/Static.lhs
  iohk-monitoring/src/Cardano/BM/Data/Output.lhs
  iohk-monitoring/test/Cardano/BM/Test/Configuration.lhs
  iohk-monitoring/test/Cardano/BM/Test/Routing.lhs
  iohk-monitoring/test/Cardano/BM/Test/Trace.lhs
Labels: enhancement
