Repository input-output-hk/iohk-monitoring-framework, pull requests merged in 2020-01, with the labels that each got.

#496 CAD-372 message counters removed
  iohk-monitoring/iohk-monitoring.cabal
  iohk-monitoring/src/Cardano/BM/Backend/Log.lhs
  iohk-monitoring/src/Cardano/BM/Backend/Switchboard.lhs
  iohk-monitoring/src/Cardano/BM/Data/MessageCounter.lhs
  plugins/backend-aggregation/src/Cardano/BM/Backend/Aggregation.lhs
  plugins/backend-ekg/src/Cardano/BM/Backend/EKGView.lhs
  plugins/backend-graylog/src/Cardano/BM/Backend/Graylog.lhs
  plugins/backend-monitoring/src/Cardano/BM/Backend/Monitoring.lhs
Labels: Byron

#498 CAD-371 trace acceptor plugin
  cabal.project
  iohk-monitoring/iohk-monitoring.cabal
  iohk-monitoring/src/Cardano/BM/Backend/Switchboard.lhs
  iohk-monitoring/src/Cardano/BM/Data/BackendKind.lhs
  iohk-monitoring/test/Cardano/BM/Test/Configuration.lhs
  iohk-monitoring/test/config.yaml
  nix/.stack.nix/default.nix
  nix/.stack.nix/lobemo-backend-trace-acceptor.nix
  nix/.stack.nix/lobemo-backend-trace-forwarder.nix
  plugins/backend-aggregation/src/Cardano/BM/Backend/Aggregation.lhs
  plugins/backend-editor/src/Cardano/BM/Backend/Editor.lhs
  plugins/backend-ekg/src/Cardano/BM/Backend/EKGView.lhs
  plugins/backend-graylog/src/Cardano/BM/Backend/Graylog.lhs
  plugins/backend-monitoring/src/Cardano/BM/Backend/Monitoring.lhs
  plugins/backend-trace-acceptor/LICENSE
  plugins/backend-trace-acceptor/NOTICE
  plugins/backend-trace-acceptor/README.md
  plugins/backend-trace-acceptor/Setup.hs
  plugins/backend-trace-acceptor/lobemo-backend-trace-acceptor.cabal
  plugins/backend-trace-acceptor/src/Cardano/BM/Backend/TraceAcceptor.lhs
  plugins/backend-trace-forwarder/LICENSE
  plugins/backend-trace-forwarder/NOTICE
  plugins/backend-trace-forwarder/README.md
  plugins/backend-trace-forwarder/Setup.hs
  plugins/backend-trace-forwarder/lobemo-backend-trace-forwarder.cabal
  plugins/backend-trace-forwarder/src/Cardano/BM/Backend/TraceForwarder.lhs
  plugins/scribe-systemd/src/Cardano/BM/Scribe/Systemd.lhs
  stack.yaml
Labels: Byron

#501 CAD-407 fix Linux counters
  iohk-monitoring/src/Cardano/BM/Counters/Linux.lhs
Labels: Byron, bug

#502 CAD-406 fixed space leak in LogBuffer
  iohk-monitoring/src/Cardano/BM/Backend/LogBuffer.lhs
  iohk-monitoring/src/Cardano/BM/Data/Aggregated.lhs
  iohk-monitoring/src/Cardano/BM/Data/Counter.lhs
Labels: Byron, bug

#503 CAD-403: add a test for `defaultConfigStdout` roundtrip & fix it
  iohk-monitoring/src/Cardano/BM/Configuration/Model.lhs
  iohk-monitoring/test/Cardano/BM/Test/Configuration.lhs
Labels: test

#507 CAD-438 replacement for Prometheus adaptor
  cabal.project
  examples/complex/Main.lhs
  examples/lobemo-examples.cabal
  nix/.stack.nix/default.nix
  nix/.stack.nix/ekg-prometheus-adapter.nix
  nix/.stack.nix/lobemo-backend-ekg.nix
  nix/.stack.nix/lobemo-backend-prometheus.nix
  plugins/backend-ekg/lobemo-backend-ekg.cabal
  plugins/backend-ekg/src/Cardano/BM/Backend/Prometheus.lhs
  stack.yaml
Labels: Byron, bug

#508 CAD-438 fix binding IP address; only display numeric values
  plugins/backend-ekg/src/Cardano/BM/Backend/Prometheus.lhs
Labels: Byron, bug

#510 CAD-425 journald scribe
  examples/complex/Main.lhs
  examples/lobemo-examples.cabal
  examples/simple/Main.lhs
  iohk-monitoring/src/Cardano/BM/Backend/Log.lhs
  iohk-monitoring/src/Cardano/BM/Data/Output.lhs
  nix/.stack.nix/lobemo-examples.nix
  plugins/scribe-systemd/src/Cardano/BM/Scribe/Systemd.lhs
Labels: Byron

#511 CAD-404 archiving Synopsizer code
  examples/complex/Main.lhs
  iohk-monitoring/src/Cardano/BM/Data/Tracer.lhs
  iohk-monitoring/src/Cardano/BM/Data/Transformers.lhs
  iohk-monitoring/test/Cardano/BM/Test/Trace.lhs
  tracer-transformers/src/Control/Tracer/Transformers/Synopsizer.lhs
  tracer-transformers/tracer-transformers.cabal
Labels: Byron
